/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p66.reto5.vista;

/**
 *
 * @author nana
 */
public class VentanaGenerarReporte extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGenerarReporte
     */
    public VentanaGenerarReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jinformes = new javax.swing.JLabel();
        jContenido = new javax.swing.JLabel();
        btnConsulta = new java.awt.Button();
        cboxOptions = new javax.swing.JComboBox<>();

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C&F Construcciones y Futuro");
        setBackground(java.awt.Color.darkGray);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTitulo.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTitulo.setText("C&F Construcciones y Futuro");
        jTitulo.setIconTextGap(6);

        jinformes.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jinformes.setText("Informes");

        jContenido.setText("Seleccione el informe que desea visualizar");

        btnConsulta.setBackground(java.awt.Color.lightGray);
        btnConsulta.setLabel("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        cboxOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informe 1", "Informe 2", "Informe 3", " " }));
        cboxOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxOptionsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jinformes)
                            .add(jTitulo)
                            .add(jContenido, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 394, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 51, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(cboxOptions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 217, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(47, 47, 47)
                        .add(btnConsulta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(63, 63, 63)
                .add(jTitulo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jinformes)
                .add(60, 60, 60)
                .add(jContenido)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnConsulta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cboxOptions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 12, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxOptionsActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        int opcion = cboxOptions.getSelectedIndex();
        switch (opcion) {
            case 0:
                VentanaRequerimiento1 vr1 = new VentanaRequerimiento1();
                vr1.setVisible(true);
                vr1.generarTabla();
                break;
            case 1:
                VentanaRequerimiento2 vr2 = new VentanaRequerimiento2();
                vr2.setVisible(true);
                vr2.generarTabla();                
                break;
            case 2:
                VentanaRequerimiento3 vr3 = new VentanaRequerimiento3();
                vr3.setVisible(true);
                vr3.generarTabla();                
                break;
        }
    }//GEN-LAST:event_btnConsultaActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button btnConsulta;
    private javax.swing.JComboBox<String> cboxOptions;
    private javax.swing.JLabel jContenido;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JLabel jinformes;
    // End of variables declaration//GEN-END:variables
}
